# Generated by Django 4.2 on 2023-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file_name', models.CharField(max_length=300, verbose_name='исходное имя файла')),
                ('new_file_name', models.CharField(blank=True, max_length=300, verbose_name='новое имя файла')),
                ('download_link', models.URLField(blank=True, max_length=1000, verbose_name='ссылка для скачивания')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_for_delete', models.CharField(blank=True, max_length=23, verbose_name='Время удаления(сек.)')),
                ('file', models.FileField(upload_to='product_files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'файл товара',
                'verbose_name_plural': 'файлы товаров',
                'ordering': ['-created_at'],
            },
        ),
    ]
