# Generated by Django 4.2 on 2023-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0002_remove_productfiles_new_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfiles',
            name='is_links_list',
            field=models.BooleanField(default=False, verbose_name='Список ссылок'),
        ),
    ]
