# Generated by Django 4.2 on 2023-04-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfiles',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_store.category', verbose_name='Папка'),
            preserve_default=False,
        ),
    ]
