# Generated by Django 4.2 on 2023-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0007_alter_productfiles_time_for_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfiles',
            name='time_for_delete',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время удаления'),
        ),
    ]
